// Code generated by Prismic. DO NOT EDIT.

import Hero from './Hero';
import BentoBox from './BentoBox';
import ColorChanger from './ColorChanger';

export const components = {
  hero: Hero,
  bento_box: BentoBox,
  color_changer: ColorChanger,
};
